### PR TITLE
Fixed blank page issue

### PR DESCRIPTION
**Pull request by subashpaul**

### CODE REVIEW

**Comment by SWELLZ** [comment]
This PR does not fix bug for this issue. The bug is as follows:
- Edit deck name
- Without refresh, click the deck you just edited
- When clicked, the page displays nothing unless you refresh

The behavior of this PR still contains that bug. Here is the expected behavior:
- Edit deck name or description
- Without refresh, click the edited deck
- The deck info and cards should be displayed without refresh

**Review by NehemiahDias — CHANGES_REQUESTED** [review]
This PR does not fix bug for this issue. The bug is as follows:
- Edit deck name
- Without refresh, click the deck you just edited
- When clicked, the page displays nothing unless you refresh

The behavior of this PR still contains that bug. Here is the expected behavior:
- Edit deck name or description
- Without refresh, click the edited deck
- The deck info and cards should be displayed without refresh

**Comment by subashpaul** [comment]
> 

I have realized and fixed this issue as well....can i raise a PR now?

**Comment by subashpaul** [comment]
I was just a small error....well it feels exhausting if your PR deosn't gets merged after spending hours on it...
Hope You understand...How can i get it merged now?

**Comment by NehemiahDias** [comment]
@subashpaul I understand but the issue has been closed, sorry. You can look out for any more open issues from me and help out with anything else you're interested in

**Pull request closed without merging**
